import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNav from './MainNav/MainNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({
    children,
}: {
    children: React.ReactNode
}) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='grid grid-cols-[1fr_3fr]'>
                    <MainNav />
                    {children}
                </div>
            </body>
        </html>
    )
}

export default RootLayout;